#!/usr/bin/env ansible-playbook

---

# Install Vim.
- name: get vim.msi on windows
  win_get_url:
    url: '{{ vim_msi_url }}'
    dest: '{{ tmp_path }}\{{ vim_msi_filename }}'

- name: install vim with msi
  win_msi:
    path: '{{ tmp_path }}\{{ vim_msi_filename }}'

#- name: use dark background in vim
#  win_lineinfile:
#    dest: '{{ vimrc_path }}\_vimrc'
#    line: 'set background=dark'

# vim:ft=ansible :
